version: "3.3"

networks:
  kingwangjjang-network:
    external: true

services:
  kingwangjjang-api-gateway:
    container_name: kingwangjjang-api-gateway
    image: ${DOCKERHUB_USERNAME}/api-gateway:0.0.1
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/var/log
    networks:
      - kingwangjjang-network
    depends_on:
      - kingwangjjang-user-service
      - kingwangjjang-board-service
      - kingwangjjang-comment-service

  kingwangjjang-board-service:
    container_name: kingwangjjang-board-service
    image: ${DOCKERHUB_USERNAME}/board-service:0.0.1
    env_file:
      - .env
    volumes:
      - ./logs:/var/log
    networks:
      - kingwangjjang-network
    depends_on:
      - kingwangjjang-user-service
      - kingwangjjang-comment-service

  kingwangjjang-user-service:
    container_name: kingwangjjang-user-service
    image: ${DOCKERHUB_USERNAME}/user-service:0.0.1
    env_file:
      - .env
    volumes:
      - ./logs:/var/log
    networks:
      - kingwangjjang-network

  kingwangjjang-comment-service:
    container_name: kingwangjjang-comment-service
    image: ${DOCKERHUB_USERNAME}/comment-service:0.0.1
    env_file:
      - .env
    volumes:
      - ./logs:/var/log
    networks:
      - kingwangjjang-network
