# Generated by Django 4.1.13 on 2024-03-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RealTime',
            fields=[
                ('_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=125)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('create_time', models.DateTimeField()),
                ('GPTAnswer', models.TextField()),
            ],
            options={
                'db_table': 'realtimebest',
            },
        ),
    ]
