# Generated by Django 4.1.13 on 2024-04-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=125)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('create_time', models.DateTimeField()),
                ('GPTAnswer', models.TextField(default='GPT 생성 중입니다. 이미지가 많은 경우 오래 걸립니다.')),
            ],
            options={
                'db_table': 'dailybest',
            },
        ),
        migrations.CreateModel(
            name='RealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=125)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('create_time', models.DateTimeField()),
                ('GPTAnswer', models.TextField(default='GPT 생성 중입니다. 이미지가 많은 경우 오래 걸립니다.')),
            ],
            options={
                'db_table': 'realtimebest',
            },
        ),
    ]
