[tool.poetry]
name = "board-service"
version = "0.1.0"
description = "about board"
authors = ["hwanju <hwanju1596@gmail.com>"]
readme = "README.md"
package-mode = false
[tool.poetry.dependencies]
python = "^3.12"
annotated-types = "^0.7.0"
anyio = "^4.13.0"
certifi = "^2026.5.20"
click = "^8.4.1"
colorama = "^0.4.6"
email-validator = "^2.3.0"
fastapi = "^0.136.3"
fastapi-cli = "^0.0.24"
h11 = "^0.16.0"
httpcore = "^1.0.9"
httptools = "^0.8.0"
httpx = "^0.28.1"
idna = "^3.16"
itsdangerous = "^2.2.0"
jinja2 = "^3.1.6"
markdown-it-py = "^4.2.0"
markupsafe = "^3.0.3"
mdurl = "^0.1.2"
orjson = "^3.11.9"
typing-extensions = "^4.15.0"

pydantic = "^2.13.4"
pydantic-core = "2.46.4"
pydantic-settings = "^2.14.1"
pydantic-extra-types = "^2.11.1"
pygments = "^2.20.0"
python-dotenv = "^1.2.2"
python-multipart = "^0.0.29"
pyyaml = "^6.0.3"
rich = "^15.0.0"
shellingham = "^1.5.4"
sniffio = "^1.3.1"
starlette = "^1.1.0"
typer = "^0.26.1"
ujson = "^5.12.1"
uvicorn = "^0.48.0"
watchfiles = "^1.2.0"
websockets = "^16.0"
pytest = "^9.0.3"
pytest-asyncio = "^1.4.0"
alembic = "^1.18.4"
langsmith = "^0.8.5"
ollama = "^0.6.2"
poetry = "^2.4.1"
selenium = "^4.44.0"
langchain = "^1.3.2"
langchain-community = "^0.4.2"
langchain-openai = "^1.2.2"
beautifulsoup4 = "^4.14.3"
pytesseract = "^0.3.13"
pillow = "^12.2.0"
opencv-python = "^4.13.0.92"
oauth2client = "^4.1.3"
google-auth = "^2.53.0"
google-auth-oauthlib = "^1.4.0"
google-auth-httplib2 = "^0.4.0"
google-api-python-client = "^2.196.0"
authlib = "^1.7.2"
faker = "^40.19.1"
lxml = "^6.1.1"
pyjwt = "^2.13.0"
boto3 = "^1.43.15"
schedule = "^1.2.2"
sqlalchemy = "^2.0.50"
psycopg = {extras = ["binary"], version = "^3.3.4"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
